// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Porsche-ths/weather-4-u/geolocation-service/internal/api/geocode"
	"github.com/Porsche-ths/weather-4-u/geolocation-service/internal/api/geoip"
	"github.com/Porsche-ths/weather-4-u/geolocation-service/internal/config"
	"github.com/Porsche-ths/weather-4-u/geolocation-service/internal/geoapify"
)

// Injectors from wire.go:

func Intialize() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	client, err := geoapify.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	service := geocode.NewService(client)
	handler := geocode.NewHandler(service)
	geoipService := geoip.NewService(client)
	geoipHandler := geoip.NewHandler(geoipService)
	app := New(configConfig, handler, geoipHandler)
	return app, nil
}
