import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopMenu from "@/components/topMenu";
import Bg from "@/components/bg";
import Image from "next/image";
import { PublicEnvScript } from "next-runtime-env";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Weather 4 U",
  description: "Generated by Porsche and His (slave)Team",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Bg />
        <div className="relative z-10">
          <TopMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
