// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Porsche-ths/weather-4-u/weather-service/internal/api"
	"github.com/Porsche-ths/weather-4-u/weather-service/internal/client"
	"github.com/Porsche-ths/weather-4-u/weather-service/internal/config"
)

// Injectors from wire.go:

func Initialize() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	clientClient, err := client.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	service := api.NewService(clientClient)
	handler := api.NewHandler(service)
	app := New(configConfig, handler)
	return app, nil
}
