services:
  weather-service:
    container_name: weather-service
    image: weather-service:latest
    build:
      context: .
    ports:
      - "8082:8082"
    networks:
      - app-net
    environment:
      - PORT=8082
      - DEV=FALSE
      - OPENWEATHER_API_ENDPOINT=https://api.openweathermap.org/data/2.5/
    env_file: ".env"
