services:
  geolocation-service:
    container_name: geolocation-service
    image: geolocation-service:latest
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DEV=FALSE
      - GEOAPIFY_API_ENDPOINT=https://api.geoapify.com/
    env_file: ".env"
